replicaCount: 1
image:
  repository: castai/central_hibernate_manager
  tag: latest
  pullPolicy: IfNotPresent

secret:
  apiKey: "eW91cl9hcGlfa2V5"  # Base64 encoded

config:
  instanceType: "t3.large"
  schedules:
    - cluster_id: cluster1
      hibernate_cron: "0 22 * * *"
      resume_cron: "0 8 * * *"
    - cluster_id: cluster2
      hibernate_cron: "0 23 * * *"
      resume_cron: "0 9 * * *"
