apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-hibernate-manager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cast-hibernate-manager
  template:
    metadata:
      labels:
        app: cast-hibernate-manager
    spec:
      containers:
      - name: scheduler
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: INSTANCE_TYPE
          value: {{ .Values.instanceType }}
        envFrom:
        - secretRef:
            name: {{ .Values.apiKey.secretName }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/schedule
      volumes:
      - name: config-volume
        configMap:
          name: schedule-config
