apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cluster-scheduler
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-scheduler
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-scheduler
    spec:
      containers:
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: INSTANCE_TYPE
              value: {{ .Values.config.instanceType }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-api-key-secret
          volumeMounts:
            - name: config-volume
              mountPath: /etc/schedule
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-schedule-config
