replicaCount: 1

image:
  repository: castai/central_hibernate_manager
  tag: latest
  pullPolicy: IfNotPresent

apiKey:
  secretName: cast-api-key-secret
  secretKey: api-key

instanceType: t2.medium

schedules:
  - cluster_id: cluster1
    hibernate_cron: "0 22 * * *"
    resume_cron: "0 8 * * *"
  - cluster_id: cluster2
    hibernate_cron: "0 23 * * *"
    resume_cron: "0 9 * * *"
